import { Review, Escalation, DashboardMetrics, ReputationReport } from "@/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

export const DEMO_REVIEWS: Review[] = [
  {
    id: "rev-1",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-001",
    author_name: "Thandi M.",
    author_avatar: null,
    rating: 5,
    text: "Absolutely brilliant service! Dr Naidoo was so thorough and gentle. The whole team made me feel at ease. Highly recommend to anyone in the area.",
    sentiment: "positive",
    responded: true,
    escalated: false,
    created_at: daysAgo(1),
    source_created_at: daysAgo(1),
  },
  {
    id: "rev-2",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-002",
    author_name: "Johan V.",
    author_avatar: null,
    rating: 4,
    text: "Good experience overall. Wait time was a bit long but the treatment was professional and thorough.",
    sentiment: "positive",
    responded: true,
    escalated: false,
    created_at: daysAgo(2),
    source_created_at: daysAgo(2),
  },
  {
    id: "rev-3",
    business_id: "biz-1",
    source: "facebook",
    source_review_id: "f-001",
    author_name: "Sipho K.",
    author_avatar: null,
    rating: 2,
    text: "Very disappointed. Had to wait over an hour past my appointment time and the receptionist was rude. Won't be coming back.",
    sentiment: "negative",
    responded: false,
    escalated: true,
    created_at: daysAgo(3),
    source_created_at: daysAgo(3),
  },
  {
    id: "rev-4",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-003",
    author_name: "Lerato P.",
    author_avatar: null,
    rating: 5,
    text: "Best dentist in Joburg! Clean, modern practice and the staff are always friendly. Love the online booking system too.",
    sentiment: "positive",
    responded: true,
    escalated: false,
    created_at: daysAgo(5),
    source_created_at: daysAgo(5),
  },
  {
    id: "rev-5",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-004",
    author_name: "David R.",
    author_avatar: null,
    rating: 3,
    text: "Decent service but a bit pricey for what you get. The cleaning was fine but nothing special.",
    sentiment: "neutral",
    responded: false,
    escalated: false,
    created_at: daysAgo(7),
    source_created_at: daysAgo(7),
  },
  {
    id: "rev-6",
    business_id: "biz-1",
    source: "facebook",
    source_review_id: "f-002",
    author_name: "Naledi S.",
    author_avatar: null,
    rating: 1,
    text: "Terrible experience. They charged me for a procedure I didn't agree to. Trying to get a refund and no one is returning my calls.",
    sentiment: "negative",
    responded: false,
    escalated: true,
    created_at: daysAgo(4),
    source_created_at: daysAgo(4),
  },
  {
    id: "rev-7",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-005",
    author_name: "Pieter D.",
    author_avatar: null,
    rating: 5,
    text: "Fantastic experience from start to finish. The team is professional and caring. Would definitely recommend!",
    sentiment: "positive",
    responded: true,
    escalated: false,
    created_at: daysAgo(8),
    source_created_at: daysAgo(8),
  },
  {
    id: "rev-8",
    business_id: "biz-1",
    source: "google",
    source_review_id: "g-006",
    author_name: "Amina B.",
    author_avatar: null,
    rating: 4,
    text: "Very happy with my visit. The hygienist explained everything clearly and was very gentle. Parking was easy too.",
    sentiment: "positive",
    responded: true,
    escalated: false,
    created_at: daysAgo(10),
    source_created_at: daysAgo(10),
  },
];

export const DEMO_ESCALATIONS: Escalation[] = [
  {
    id: "esc-1",
    review_id: "rev-3",
    business_id: "biz-1",
    status: "pending",
    assigned_to: null,
    notes: null,
    created_at: daysAgo(3),
    resolved_at: null,
    review: DEMO_REVIEWS[2],
  },
  {
    id: "esc-2",
    review_id: "rev-6",
    business_id: "biz-1",
    status: "in_progress",
    assigned_to: "Practice Manager",
    notes: "Called customer, awaiting callback",
    created_at: daysAgo(4),
    resolved_at: null,
    review: DEMO_REVIEWS[5],
  },
];

export const DEMO_METRICS: DashboardMetrics = {
  totalReviews: 127,
  averageRating: 4.3,
  responseRate: 0.82,
  pendingEscalations: 2,
  reviewsThisMonth: 14,
  ratingTrend: 0.2,
  sentimentBreakdown: {
    positive: 78,
    neutral: 31,
    negative: 18,
  },
  recentReviews: DEMO_REVIEWS.slice(0, 5),
  ratingOverTime: [
    { date: "Jan", rating: 4.1, count: 12 },
    { date: "Feb", rating: 4.0, count: 15 },
    { date: "Mar", rating: 4.2, count: 11 },
    { date: "Apr", rating: 4.4, count: 18 },
    { date: "May", rating: 4.3, count: 14 },
    { date: "Jun", rating: 4.5, count: 16 },
  ],
};

export const DEMO_REPORT: ReputationReport = {
  id: "rpt-1",
  business_id: "biz-1",
  period_start: daysAgo(30),
  period_end: daysAgo(0),
  total_reviews: 14,
  average_rating: 4.3,
  response_rate: 0.82,
  sentiment_breakdown: { positive: 8, neutral: 3, negative: 3 },
  top_keywords: ["professional", "friendly", "wait time", "clean", "recommend"],
  recommendations: [
    "Reduce average wait times — 30% of neutral/negative reviews mention delays.",
    "Train reception staff on customer communication — flagged in 2 negative reviews.",
    "Encourage happy patients to leave reviews after their visit to boost volume.",
    "Respond to all negative reviews within 4 hours to improve recovery rate.",
    "Highlight your online booking system in marketing — it is frequently praised.",
  ],
  created_at: daysAgo(0),
};
