import { Radar } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] px-4 py-12">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="mb-8 inline-flex items-center gap-2">
          <Radar className="h-6 w-6 text-cyan-400" />
          <span className="text-lg font-bold text-white">ReviewRadar</span>
        </Link>

        <h1 className="mt-8 text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/40">Last updated: May 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-white/60">
          <section>
            <h2 className="text-lg font-semibold text-white">1. Agreement</h2>
            <p className="mt-2">
              By accessing or using ReviewRadar (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
              The Service is provided by ReviewRadar (Pty) Ltd, a South African company.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">2. Service Description</h2>
            <p className="mt-2">
              ReviewRadar provides AI-powered review management for South African local businesses, including:
            </p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>Aggregation of customer reviews from Google and Facebook</li>
              <li>AI-generated review responses using your configured brand voice</li>
              <li>Escalation workflow for negative reviews</li>
              <li>Monthly reputation reports with actionable insights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">3. Account Responsibilities</h2>
            <p className="mt-2">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities
              that occur under your account. You must provide accurate and complete information during registration.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">4. Subscription and Payment</h2>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>ReviewRadar offers a 14-day free trial. No credit card is required to start.</li>
              <li>After the trial, continued use requires a paid subscription (Starter, Pro, or Enterprise).</li>
              <li>All prices are in South African Rand (ZAR) and include VAT where applicable.</li>
              <li>Payments are processed securely via PayFast.</li>
              <li>Subscriptions are billed monthly. You may cancel at any time; access continues until the end of the billing period.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">5. AI-Generated Content</h2>
            <p className="mt-2">
              Review responses generated by our AI are suggestions only. You are responsible for reviewing and approving
              all responses before they are posted to public platforms. ReviewRadar is not liable for any consequences
              arising from AI-generated content that you choose to publish.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">6. Acceptable Use</h2>
            <p className="mt-2">You agree not to:</p>
            <ul className="mt-2 list-disc pl-6 space-y-1">
              <li>Use the Service to generate fake reviews or misleading responses</li>
              <li>Exceed the usage limits of your subscription tier</li>
              <li>Attempt to access other users&apos; data or accounts</li>
              <li>Use the Service in any way that violates applicable South African law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">7. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by South African law, ReviewRadar shall not be liable for any indirect,
              incidental, special, or consequential damages arising from the use of the Service, including but not
              limited to loss of revenue, reputation, or data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">8. Governing Law</h2>
            <p className="mt-2">
              These Terms are governed by the laws of the Republic of South Africa. Any disputes shall be
              subject to the exclusive jurisdiction of the South African courts.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">9. Contact</h2>
            <p className="mt-2">
              For any questions regarding these Terms, please contact us at{" "}
              <span className="text-cyan-400">legal@reviewradar.co.za</span>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
